# this is the name of workflow
name: Hello Workflow

on:
  push:
    branches : [main] 
#this are jobs inside workflows
jobs:
  # this is name o workflows
  greet:
    runs-on: ubuntu-latest
    #
    steps:
      - name: say hello to users
        run: echo "hello Dosto"

      - name: say hello to username 
        run: echo "hello $USER"
