# this is the name of workflow
name: Hello Workflow

on:
  workflow_dispatch: 
  
#this are jobs inside workflows
jobs:
  # this is name o workflows
  greet:
    runs-on: ubuntu-latest
    #
    steps:
      - name: say hello to users
        run: echo "hello Dosto"

      - name: say hello to username 
        run: echo "hello $USER"
        
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello from GitHub Actions!"

      - name: Show Date
        run: date

      - name: List Files
        run: ls -la

      - name: Runner OS
        run: uname -a
